import busImg from '/src/assets/images/bus-card/bus.png'
import seatIcon from '/src/assets/icons/bus-card/seat.svg'
import seatBeltIcon from '/src/assets/icons/bus-card/seat-belt.svg'
import flashIcon from '/src/assets/icons/bus-card/flash.svg'
import airConIcon from '/src/assets/icons/bus-card/air-conditioner.svg'
import karaokeIcon from '/src/assets/icons/bus-card/karaoke.svg'
import wcIcon from '/src/assets/icons/bus-card/WC.svg'

import minivanIcon from '/src/assets/icons/filter/minivan.svg'
import microbusIcon from '/src/assets/icons/filter/microbus.svg'
import busesIcon from '/src/assets/icons/filter/buses.svg'
import allIcon from '/src/assets/icons/filter/all.svg'

// export const buses = [
//     {
//         id: 1,
//         name: "Автобус Yutong ZK6122H9",
//         rating: 4.7,
//         image: busImg,
//         amenities: [
//             { icon: seatIcon, text: "Мест: 53" },
//             { icon: seatBeltIcon, text: "Ремни безопасности" },
//             { icon: flashIcon, text: "Розетки" },
//             { icon: airConIcon, text: "Кондиционер" },
//             { icon: karaokeIcon, text: "Микрофон" },
//             { icon: wcIcon, text: "Туалет" },
//         ],
//         price: "1500 ₽",
//     },
//     {
//         id: 2,
//         name: "Автобус Mercedes-Benz Sprinter",
//         rating: 4.5,
//         image: busImg,
//         amenities: [
//             { icon: seatIcon, text: "Мест: 53" },
//             { icon: seatBeltIcon, text: "Ремни безопасности" },
//             { icon: flashIcon, text: "Розетки" },
//             { icon: airConIcon, text: "Кондиционер" },
//             { icon: karaokeIcon, text: "Микрофон" },
//             { icon: wcIcon, text: "Туалет" },
//         ],
//         price: "1200 ₽",
//     },
//     {
//         id: 3,
//         name: "Автобус Setra S 415",
//         rating: 4.8,
//         image: busImg,
//         amenities: [
//             { icon: seatIcon, text: "Мест: 53" },
//             { icon: seatBeltIcon, text: "Ремни безопасности" },
//             { icon: flashIcon, text: "Розетки" },
//             { icon: airConIcon, text: "Кондиционер" },
//             { icon: karaokeIcon, text: "Микрофон" },
//             { icon: wcIcon, text: "Туалет" },
//         ],
//         price: "1800 ₽",
//     },
//     {
//         id: 4,
//         name: "Автобус Volvo 9700",
//         rating: 4.6,
//         image: busImg,
//         amenities: [
//             { icon: seatIcon, text: "Мест: 53" },
//             { icon: seatBeltIcon, text: "Ремни безопасности" },
//             { icon: flashIcon, text: "Розетки" },
//             { icon: airConIcon, text: "Кондиционер" },
//             { icon: karaokeIcon, text: "Микрофон" },
//             { icon: wcIcon, text: "Туалет" },
//         ],
//         image: busImg,
//     },
// ];

export const BUS_CATEGORIES = [
    {
        id: 1,
        title: "Для экскурсий",
        buses: [
            {
                id: 1,
                name: "Автобус Yutong ZK6122H9",
                rating: 4.7,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1500 ₽",
            },
            {
                id: 2,
                name: "Автобус Mercedes-Benz Sprinter",
                rating: 4.5,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1200 ₽",
            },
            {
                id: 3,
                name: "Автобус Setra S 415",
                rating: 4.8,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1800 ₽",
            },
            {
                id: 4,
                name: "Автобус Volvo 9700",
                rating: 4.6,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1900 ₽",
            },
            {
                id: 5,
                name: "Автобус Yutong ZK6122H9",
                rating: 4.7,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1500 ₽",
            },
            {
                id: 6,
                name: "Автобус Mercedes-Benz Sprinter",
                rating: 4.5,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1200 ₽",
            },
            {
                id: 7,
                name: "Автобус Setra S 415",
                rating: 4.8,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1800 ₽",
            },
            {
                id: 8,
                name: "Автобус Volvo 9700",
                rating: 4.6,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "2100 ₽",
            },
        ],
    },
    {
        id: 2,
        title: "Для мероприятий",
        buses: [
            {
                id: 1,
                name: "Автобус Mercedes-Benz Sprinter",
                rating: 4.5,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1200 ₽",
            },
            {
                id: 2,
                name: "Автобус Mercedes-Benz Sprinter",
                rating: 4.5,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1200 ₽",
            },
            {
                id: 3,
                name: "Автобус Setra S 415",
                rating: 4.8,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1800 ₽",
            },
            {
                id: 4,
                name: "Автобус Volvo 9700",
                rating: 4.6,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "3100 ₽",
            },
            {
                id: 5,
                name: "Автобус Yutong ZK6122H9",
                rating: 4.7,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1500 ₽",
            },
            {
                id: 6,
                name: "Автобус Mercedes-Benz Sprinter",
                rating: 4.5,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1200 ₽",
            },
            {
                id: 7,
                name: "Автобус Setra S 415",
                rating: 4.8,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1800 ₽",
            },
            {
                id: 8,
                name: "Автобус Volvo 9700",
                rating: 4.6,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "2100 ₽",
            },
        ],
    },
    {
        id: 3,
        title: "Для вечеринок",
        buses: [
            {
                id: 1,
                name: "Автобус Setra S 415",
                rating: 4.8,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1800 ₽",
            },
            {
                id: 2,
                name: "Автобус Mercedes-Benz Sprinter",
                rating: 4.5,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1200 ₽",
            },
            {
                id: 3,
                name: "Автобус Setra S 415",
                rating: 4.8,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1800 ₽",
            },
            {
                id: 4,
                name: "Автобус Volvo 9700",
                rating: 4.6,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "2900 ₽",
            },
            {
                id: 5,
                name: "Автобус Yutong ZK6122H9",
                rating: 4.7,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1500 ₽",
            },
            {
                id: 6,
                name: "Автобус Mercedes-Benz Sprinter",
                rating: 4.5,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1200 ₽",
            },
            {
                id: 7,
                name: "Автобус Setra S 415",
                rating: 4.8,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1800 ₽",
            },
            {
                id: 8,
                name: "Автобус Volvo 9700",
                rating: 4.6,
                image: busImg,
                amenities: [
                    { icon: seatIcon, text: "Мест: 53" },
                    { icon: seatBeltIcon, text: "Ремни безопасности" },
                    { icon: flashIcon, text: "Розетки" },
                    { icon: airConIcon, text: "Кондиционер" },
                    { icon: karaokeIcon, text: "Микрофон" },
                    { icon: wcIcon, text: "Туалет" },
                ],
                price: "1900 ₽",
            },
        ],
    },
];

export const FILTERS = [
    {
        id: 1,
        name: "Минивэны",
        src: minivanIcon,
    },
    {
        id: 2,
        name: "Микроавтобусы",
        src: microbusIcon,
    },
    {
        id: 3,
        name: "Автобусы",
        src: busesIcon,
    },
    {
        id: 4,
        name: "Все типы",
        src: allIcon,
    },
]